# Generated by Django 4.1.3 on 2022-11-03 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='menuItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('name', models.CharField(max_length=50)),
                ('updated_last', models.TimeField()),
                ('creation_date', models.TimeField()),
            ],
        ),
    ]
